### ISSUE TITLE
AttributeError: module 'typing' has no attribute '_ClassVar'

### ISSUE THREAD

**Issue by htlcnn** [speckleworks/PySpeckle#25]
I installed speckle using pip, but I couldn't import it
```
PS C:\Users\HTL> python
Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from speckle import SpeckleApiClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python372\Lib\site-packages\speckle\__init__.py", line 1, in <module>
    from .SpeckleClient import SpeckleApiClient, jdumps
  File "C:\Program Files\Python372\Lib\site-packages\speckle\SpeckleClient.py", line 4, in <module>
    from speckle.base.client import ClientBase
  File "C:\Program Files\Python372\Lib\site-packages\speckle\base\client.py", line 28, in <module>
    from speckle import resources
  File "C:\Program Files\Python372\Lib\site-packages\speckle\resources\__init__.py", line 1, in <module>
    from speckle.base.resource import ResourceBase
  File "C:\Program Files\Python372\Lib\site-packages\speckle\base\resource.py", line 3, in <module>
    from pydantic import BaseModel
  File "C:\Program Files\Python372\Lib\site-packages\pydantic\__init__.py", line 2, in <module>
    from . import dataclasses
  File "C:\Program Files\Python372\Lib\site-packages\pydantic\dataclasses.py", line 4, in <module>
    from .class_validators import gather_validators
  File "C:\Program Files\Python372\Lib\site-packages\pydantic\class_validators.py", line 20, in <module>
    @dataclass
  File "C:\Program Files\Python372\Lib\site-packages\dataclasses.py", line 958, in dataclass
    return wrap(_cls)
  File "C:\Program Files\Python372\Lib\site-packages\dataclasses.py", line 950, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "C:\Program Files\Python372\Lib\site-packages\dataclasses.py", line 801, in _process_class
    for name, type in cls_annotations.items()]
  File "C:\Program Files\Python372\Lib\site-packages\dataclasses.py", line 801, in <listcomp>
    for name, type in cls_annotations.items()]
  File "C:\Program Files\Python372\Lib\site-packages\dataclasses.py", line 659, in _get_field
    if (_is_classvar(a_type, typing)
  File "C:\Program Files\Python372\Lib\site-packages\dataclasses.py", line 550, in _is_classvar
    return type(a_type) is typing._ClassVar
AttributeError: module 'typing' has no attribute '_ClassVar'
>>>
```
Is there any requirement?

---

**Update**: I installed speckle with Python 3.6.8 and was able to use it.

**Comment by tsvilans** [comment]
The `pydantic` dependency has some of its own dependencies, one of which used to be `typing`. As of Python 3.something, `typing` is integrated, but pulling `pydantic` with `pip` still installs it.

The simple solution is just to find the `typing` module in your `site packages` folder and delete it. 

I've got a solution that avoids installing it which I will try to implement sometime soon.

**Comment by htlcnn** [comment]
`typing` is in `lib` folder. It's stdlib so I think I should not delete it in order to keep other packages working properly (if any of them use `typing`).
I'll use python<=3.6 for speckle.
Thanks.

**Comment by tsvilans** [comment]
You can also try installing `pydantic` with the `--no-deps` argument before you install `speckle`, this seems to work.

**Comment by htlcnn** [comment]
@tsvilans I tried installing `pydantic` with `--no-deps` argument, then install `speckle`. Still the same exception:
```
PS C:\WINDOWS\system32> python -m pip install -q --no-deps pydantic
PS C:\WINDOWS\system32> python -m pip install -q speckle
PS C:\WINDOWS\system32> python
Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import speckle
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python372\Lib\site-packages\speckle\__init__.py", line 1, in <module>
    from .SpeckleClient import SpeckleApiClient, jdumps
  File "C:\Program Files\Python372\Lib\site-packages\speckle\SpeckleClient.py", line 4, in <module>
    from speckle.base.client import ClientBase
  File "C:\Program Files\Python372\Lib\site-packages\speckle\base\client.py", line 28, in <module>
    from speckle import resources
  File "C:\Program Files\Python372\Lib\site-packages\speckle\resources\__init__.py", line 1, in <module>
    from speckle.base.resource import ResourceBase
  File "C:\Program Files\Python372\Lib\site-packages\speckle\base\resource.py", line 3, in <module>
    from pydantic import BaseModel
  File "C:\Program Files\Python372\Lib\site-packages\pydantic\__init__.py", line 2, in <module>
    from . import dataclasses
  File "C:\Program Files\Python372\Lib\site-packages\pydantic\dataclasses.py", line 4, in <module>
    from .class_validators import gather_validators
  File "C:\Program Files\Python372\Lib\site-packages\pydantic\class_validators.py", line 20, in <module>
    @dataclass
  File "C:\Program Files\Python372\Lib\site-packages\dataclasses.py", line 958, in dataclass
    return wrap(_cls)
  File "C:\Program Files\Python372\Lib\site-packages\dataclasses.py", line 950, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "C:\Program Files\Python372\Lib\site-packages\dataclasses.py", line 801, in _process_class
    for name, type in cls_annotations.items()]
  File "C:\Program Files\Python372\Lib\site-packages\dataclasses.py", line 801, in <listcomp>
    for name, type in cls_annotations.items()]
  File "C:\Program Files\Python372\Lib\site-packages\dataclasses.py", line 659, in _get_field
    if (_is_classvar(a_type, typing)
  File "C:\Program Files\Python372\Lib\site-packages\dataclasses.py", line 550, in _is_classvar
    return type(a_type) is typing._ClassVar
AttributeError: module 'typing' has no attribute '_ClassVar'
>>>
```

**Comment by tsvilans** [comment]
You need to get rid of the `typing` module. Python 3.7 has the necessary functionality built in.

**Comment by htlcnn** [comment]
I did `python -m pip uninstall dataclasses` and was able to `import speckle` without Exception. Was that ok?

**Comment by tsvilans** [comment]
If it works, don't touch it ;)
